require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '11.0'

target 'TaxiDriverApp' do
  use_unimodules!
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'TaxiDriverAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper-Folly' => '2.5.3' }) # update this part
  post_install do |installer|
    # delete IPHONEOS_DEPLOYMENT_TARGET for pods (using the main one)
    # installer.pods_project.targets.each do |target|
    #   target.build_configurations.each do |config|
    #     config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    #   end
    # end
    flipper_post_install(installer)
  end
end

target 'TaxiDriverApp-tvOS' do
  # Pods for TaxiDriverApp-tvOS

  target 'TaxiDriverApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
